insert into m_icons (name, path, account, filter) values ('Award', '/src/assets/icons/category/income/awards1.svg', false, 'Income');
insert into m_icons (name, path, account, filter) values ('Cupon', '/src/assets/icons/category/income/coupons1.svg', false, 'Income');
insert into m_icons (name, path, account, filter) values ('Grant', '/src/assets/icons/category/income/grants3.svg', false, 'Income');
insert into m_icons (name, path, account, filter) values ('Lottery', '/src/assets/icons/category/income/lottery2.svg', false, 'Both');
insert into m_icons (name, path, account, filter) values ('Refund', '/src/assets/icons/category/income/refunds3.svg', false, 'Income');
insert into m_icons (name, path, account, filter) values ('Rental', '/src/assets/icons/category/income/rental3.svg', false, 'Both');
insert into m_icons (name, path, account, filter) values ('Salary', '/src/assets/icons/category/income/salary2.svg', false, 'Income');
insert into m_icons (name, path, account, filter) values ('Sale', '/src/assets/icons/category/income/sale2.svg', false, true);
insert into m_icons (name, path, account, filter) values ('Food', '/src/assets/icons/category/expense/food2.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Gambling', '/src/assets/icons/category/expense/gambling3.svg', false, 'Both');
insert into m_icons (name, path, account, filter) values ('Health', '/src/assets/icons/category/expense/health1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Home', '/src/assets/icons/category/expense/home3.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Insurance', '/src/assets/icons/category/expense/insurance1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Shopping', '/src/assets/icons/category/expense/shopping1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Social', '/src/assets/icons/category/expense/social2.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Sport', '/src/assets/icons/category/expense/sport1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Tax', '/src/assets/icons/category/expense/tax3.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Telephone', '/src/assets/icons/category/expense/telephone2.svg', alse, 'Expense');
insert into m_icons (name, path, account, filter) values ('Transportation', '/src/assets/icons/category/expense/transportation2.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Baby', '/src/assets/icons/category/expense/baby3.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Beauty', '/src/assets/icons/category/expense/beauty3.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Bill', '/src/assets/icons/category/expense/bills1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Car', '/src/assets/icons/category/expense/car3.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Clothing', '/src/assets/icons/category/expense/clothing1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Education', '/src/assets/icons/category/expense/education2.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Electronic', '/src/assets/icons/category/expense/electronics1.svg', false, 'Expense');
insert into m_icons (name, path, account, filter) values ('Entertainment', '/src/assets/icons/category/expense/entertainment1.svg', false, 'Expense');
insert into m_icons (name, path, account) values ('AYA Pay', '/src/assets/icons/account/ayapay.svg', true);
insert into m_icons (name, path, account) values ('Cash', '/src/assets/icons/account/cash2.svg', true);
insert into m_icons (name, path, account) values ('Credit Card', '/src/assets/icons/account/credit-card2.svg', true);
insert into m_icons (name, path, account) values ('KBZ Pay', '/src/assets/icons/account/kpay.svg', true);
insert into m_icons (name, path, account) values ('Master Card', '/src/assets/icons/account/master-card.svg', true);
insert into m_icons (name, path, account) values ('Paypal', '/src/assets/icons/account/paypal.svg', true);
insert into m_icons (name, path, account) values ('Piggy Bank', '/src/assets/icons/account/piggy-bank1.svg', true);
insert into m_icons (name, path, account) values ('Visa Card', '/src/assets/icons/account/visa1.svg', true);
insert into m_icons (name, path, account) values ('Wallet', '/src/assets/icons/account/wallet.svg', true);
insert into m_icons (name, path, account) values ('Wave Pay', '/src/assets/icons/account/wave.svg', true);

INSERT INTO m_currencies (country, name, code) VALUES ('AFGHANISTAN', 'Afghani', 'AFN');
INSERT INTO m_currencies (country, name, code) VALUES ('ARMENIA', 'Armenian Dram', 'AMD');
INSERT INTO m_currencies (country, name, code) VALUES ('AZERBAIJAN', 'Azerbaijan Manat', 'AZN');
INSERT INTO m_currencies (country, name, code) VALUES ('BAHRAIN', 'Bahraini Dinar', 'BHD');
INSERT INTO m_currencies (country, name, code) VALUES ('BANGLADESH', 'Taka', 'BDT');
INSERT INTO m_currencies (country, name, code) VALUES ('BHUTAN', 'Ngultrum', 'BTN');
INSERT INTO m_currencies (country, name, code) VALUES ('BRUNEI DARUSSALAM', 'Brunei Dollar', 'BND');
INSERT INTO m_currencies (country, name, code) VALUES ('CAMBODIA', 'Riel', 'KHR');
INSERT INTO m_currencies (country, name, code) VALUES ('CHINA', 'Yuan Renminbi', 'CNY');
INSERT INTO m_currencies (country, name, code) VALUES ('CYPRUS', 'Euro', 'EUR');
INSERT INTO m_currencies (country, name, code) VALUES ('GEORGIA', 'Lari', 'GEL');
INSERT INTO m_currencies (country, name, code) VALUES ('HONG KONG', 'Hong Kong Dollar', 'HKD');
INSERT INTO m_currencies (country, name, code) VALUES ('INDIA', 'Indian Rupee', 'INR');
INSERT INTO m_currencies (country, name, code) VALUES ('INDONESIA', 'Rupiah', 'IDR');
INSERT INTO m_currencies (country, name, code) VALUES ('IRAN (ISLAMIC REPUBLIC OF)', 'Iranian Rial', 'IRR');
INSERT INTO m_currencies (country, name, code) VALUES ('IRAQ', 'Iraqi Dinar', 'IQD');
INSERT INTO m_currencies (country, name, code) VALUES ('ISRAEL', 'New Israeli Sheqel', 'ILS');
INSERT INTO m_currencies (country, name, code) VALUES ('JAPAN', 'Yen', 'JPY');
INSERT INTO m_currencies (country, name, code) VALUES ('JORDAN', 'Jordanian Dinar', 'JOD');
INSERT INTO m_currencies (country, name, code) VALUES ('KAZAKHSTAN', 'Tenge', 'KZT');
INSERT INTO m_currencies (country, name, code) VALUES ('KOREA (THE REPUBLIC OF)', 'Won', 'KRW');
INSERT INTO m_currencies (country, name, code) VALUES ('KUWAIT', 'Kuwaiti Dinar', 'KWD');
INSERT INTO m_currencies (country, name, code) VALUES ('KYRGYZSTAN', 'Som', 'KGS');
INSERT INTO m_currencies (country, name, code) VALUES ('LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)', 'Lao Kip', 'LAK');
INSERT INTO m_currencies (country, name, code) VALUES ('LEBANON', 'Lebanese Pound', 'LBP');
INSERT INTO m_currencies (country, name, code) VALUES ('MACAO', 'Pataca', 'MOP');
INSERT INTO m_currencies (country, name, code) VALUES ('MALAYSIA', 'Malaysian Ringgit', 'MYR');
INSERT INTO m_currencies (country, name, code) VALUES ('MALDIVES', 'Rufiyaa', 'MVR');
INSERT INTO m_currencies (country, name, code) VALUES ('MONGOLIA', 'Tugrik', 'MNT');
INSERT INTO m_currencies (country, name, code) VALUES ('MYANMAR', 'Myanmar Kyat', 'MMK');
INSERT INTO m_currencies (country, name, code) VALUES ('NEPAL', 'Nepalese Rupee', 'NPR');
INSERT INTO m_currencies (country, name, code) VALUES ('OMAN', 'Rial Omani', 'OMR');
INSERT INTO m_currencies (country, name, code) VALUES ('PAKISTAN', 'Pakistan Rupee', 'PKR');
INSERT INTO m_currencies (country, name, code) VALUES ('PHILIPPINES (THE)', 'Philippine Peso', 'PHP');
INSERT INTO m_currencies (country, name, code) VALUES ('QATAR', 'Qatari Rial', 'QAR');
INSERT INTO m_currencies (country, name, code) VALUES ('SAUDI ARABIA', 'Saudi Riyal', 'SAR');
INSERT INTO m_currencies (country, name, code) VALUES ('SINGAPORE', 'Singapore Dollar', 'SGD');
INSERT INTO m_currencies (country, name, code) VALUES ('SRI LANKA', 'Sri Lanka Rupee', 'LKR');
INSERT INTO m_currencies (country, name, code) VALUES ('SYRIAN ARAB REPUBLIC', 'Syrian Pound', 'SYP');
INSERT INTO m_currencies (country, name, code) VALUES ('TAIWAN (PROVINCE OF CHINA)', 'New Taiwan Dollar', 'TWD');
INSERT INTO m_currencies (country, name, code) VALUES ('TAJIKISTAN', 'Somoni', 'TJS');
INSERT INTO m_currencies (country, name, code) VALUES ('THAILAND', 'Baht', 'THB');
INSERT INTO m_currencies (country, name, code) VALUES ('TÜRKIYE', 'Turkish Lira', 'TRY');
INSERT INTO m_currencies (country, name, code) VALUES ('TURKMENISTAN', 'Turkmenistan New Manat', 'TMT');
INSERT INTO m_currencies (country, name, code) VALUES ('UNITED ARAB EMIRATES (THE)', 'UAE Dirham', 'AED');
INSERT INTO m_currencies (country, name, code) VALUES ('UZBEKISTAN', 'Uzbekistan Sum', 'UZS');
INSERT INTO m_currencies (country, name, code) VALUES ('VIET NAM', 'Dong', 'VND');
INSERT INTO m_currencies (country, name, code) VALUES ('YEMEN', 'Yemeni Rial', 'YER');
INSERT INTO m_currencies (country, name, code) VALUES ('UNITED STATES OF AMERICA (THE)', 'US Dollar', 'USD');
INSERT INTO m_currencies (country, name, code) VALUES ('CANADA', 'Canadian Dollar', 'CAD');
INSERT INTO m_currencies (country, name, code) VALUES ('AUSTRALIA', 'Australian Dollar', 'AUD');
INSERT INTO m_currencies (country, name, code) VALUES ('SPAIN', 'Euro', 'EUR');
INSERT INTO m_currencies (country, name, code) VALUES ('UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)', 'Pound Sterling', 'GBP');
INSERT INTO m_currencies (country, name, code) VALUES ('ITALY', 'Euro', 'EUR');
INSERT INTO m_currencies (country, name, code) VALUES ('GERMANY', 'Euro', 'EUR');
INSERT INTO m_currencies (country, name, code) VALUES ('FRANCE', 'Euro', 'EUR');